"""trips

Revision ID: 1aacc3511c5f
Revises: 46b1c4c998d5
Create Date: 2025-10-08 02:35:22.987918

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1aacc3511c5f"
down_revision: Union[str, Sequence[str], None] = "46b1c4c998d5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "trips",
        sa.Column("pk", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("taxi_id", sa.Integer(), nullable=True),
        sa.Column("x_start", sa.Integer(), nullable=False),
        sa.Column("y_start", sa.Integer(), nullable=False),
        sa.Column("x_destination", sa.Integer(), nullable=False),
        sa.Column("y_destination", sa.Integer(), nullable=False),
        sa.Column("waiting_time_minutes", sa.Integer(), nullable=False),
        sa.Column("travel_time_minutes", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["taxi_id"],
            ["taxis.pk"],
        ),
        sa.PrimaryKeyConstraint("pk"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("trips")
    # ### end Alembic commands ###
