"""callback_url

Revision ID: 40c80a56cf88
Revises: 50e933053f54
Create Date: 2025-10-09 03:53:04.384797

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "40c80a56cf88"
down_revision: Union[str, Sequence[str], None] = "50e933053f54"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("taxis", sa.Column("callback_url", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("taxis", "callback_url")
    # ### end Alembic commands ###
