# ruff: noqa
# mypy: ignore-errors
"""trips_user_id

Revision ID: 50e933053f54
Revises: 815a2e6f1460
Create Date: 2025-10-09 02:50:36.248799

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "50e933053f54"
down_revision: Union[str, Sequence[str], None] = "815a2e6f1460"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("trips", sa.Column("user_id", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("trips", "user_id")
    # ### end Alembic commands ###
