# ruff: noqa
# mypy: ignore-errors
"""trips_taxi_ondelete

Revision ID: 815a2e6f1460
Revises: 8b613e8e16a9
Create Date: 2025-10-09 02:35:10.232784

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "815a2e6f1460"
down_revision: Union[str, Sequence[str], None] = "8b613e8e16a9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("trips_taxi_id_fkey"), "trips", type_="foreignkey")
    op.create_foreign_key(
        None, "trips", "taxis", ["taxi_id"], ["pk"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "trips", type_="foreignkey")
    op.create_foreign_key(
        op.f("trips_taxi_id_fkey"), "trips", "taxis", ["taxi_id"], ["pk"]
    )
    # ### end Alembic commands ###
